apiVersion: v1
kind: Pod
metadata: 
  name: nodejs-app
  labels:
    app: njs-app
spec:
  containers: 
  - name: njs-container
    image: valentechno/nodejs1
    ports: 
    - containerPort: 9981
---
apiVersion: v1
kind: Service 
metadata: 
  name: njs-svc
spec:
  type: NodePort
  ports:
  - port: 70
    targetPort: 9981
  selector:
    app: njs-app
